{%- import "macros.jinja2.txt" as macros -%}
/*
 * MDE Datastructure Store
 * =======================
 *
 * This file has been autogenerated from an input configuration and is meant to
 * be extended by the user.
 *
 * Generated for MDE version: {{ mde_version }}
 * Builder version: {{ blp_version }}
 *
 * Please report any bugs to the project webpage.
 */

{% for item in include_files -%}
#include "{{ item }}"
{%- endfor %}
#include "{{ mde_header }}"

namespace {{ namespace_value }} {

// MDE_DEFINITIONS

{% for entity in entities %}
{{ macros.mde_declaration(entity, mde_namespace, mde_name) }}
{% endfor %}

// MDE ALIASES

{% for entity in entity_aliases %}
{{ macros.mde_aliases(entity) }}
{% endfor %}

// STATE

struct {{ state_struct_name }} {
	{% for entity in entities -%}
	{{ entity.name }} {{ entity.var_name }};
	{% endfor %}

	{{ state_struct_name }}():
	{%- for entity in entities -%}
		{{ macros.mde_constructor(entity) }}{% if not loop.last %},{% endif %}
	{%- endfor -%} {}
};

template<typename MDET>
struct InterfaceBase {

	template<typename ElementT, typename ElementArgT>
	class ConstIteratorImpl {
		using BaseConstIterator = typename MDET::PropertySet::const_iterator;
		BaseConstIterator iter;
		const ElementArgT &arg;

	public:
		using iterator_category = std::forward_iterator_tag;
		using value_type = ElementT;
		using difference_type = std::ptrdiff_t;
		using pointer = void;
		using reference = ElementT;

		ConstIteratorImpl(BaseConstIterator iter, const ElementArgT &arg)
			: iter(iter), arg(arg) {}

		const ElementT operator*() const {
			return ElementT(arg, *iter);
		}

		ConstIteratorImpl& operator++() {
			++iter;
			return *this;
		}

		bool operator!=(const ConstIteratorImpl& other) const {
			return iter != other.iter;
		}
	};

	using key_type = typename MDET::PropertyElement::InterfaceKeyType;
	using value_type = typename MDET::PropertyElement::InterfaceValueType;
	using size_type = typename MDET::PropertySet::size_type;

	using Index = typename MDET::Index;

	MDET &mde;
	const Index set_index;

	InterfaceBase(MDET &mde, Index set_index = Index()): mde(mde), set_index(set_index) {}

	bool operator<(const InterfaceBase &b) const {
		return set_index < b.set_index;
	}

	bool operator==(const InterfaceBase &b) const {
		return set_index == b.set_index;
	}

	bool is_empty() const {
		return set_index.is_empty();
	}

	bool contains(const key_type &k) const {
		return mde.contains(set_index, k);
	}

	const typename MDET::PropertySet &get_value() const {
		return mde.get_value(set_index);
	}

	std::size_t size() const {
		return mde.size_of(set_index);
	}
};

// INTERFACES

{% for entity in entities %}
{{ macros.mde_interface(entity, state_struct_name) }}
{% endfor %}

// INTERFACE ALIASES

{% for entity in interface_aliases %}
{{ macros.interface_aliases(entity) }}
{% endfor %}

// STORAGE STRUCT
struct {{ store_struct_name }} {
	{{ state_struct_name }} state;

{% for entity in entities %}
	{{ entity.interface_name }} register_{{ entity.var_name }}({{ entity.name }}::PropertySet &&g) {
		return {{ entity.interface_name }}(state, state.{{ entity.var_name }}.register_set(g));
	}

	{{ entity.interface_name }} register_{{ entity.var_name }}({{ entity.name }}::PropertySet &g) {
		return {{ entity.interface_name }}(state, state.{{ entity.var_name }}.register_set(g));
	}

	{{ entity.interface_name }} register_{{ entity.var_name }}_single({{ entity.name }}::PropertyElement &&g) {
		return {{ entity.interface_name }}(state, state.{{ entity.var_name }}.register_set_single(g));
	}

	{{ entity.interface_name }} register_{{ entity.var_name }}_single({{ entity.name }}::PropertyElement &g) {
		return {{ entity.interface_name }}(state, state.{{ entity.var_name }}.register_set_single(g));
	}

{% endfor %}
};

};