// AUTOGENERATED FILE. NOT INTENDED FOR MANUAL USAGE.
{% for item in include_files %}
#include "{{ item }}"
{%- endfor %}
#include "{{ mde_header }}"

void verify_types() {
{%- for item in eval_types %}
	using  __orch__type{{ loop.index0 }} = {{ item }};
{%- endfor %}
	return;
}